language: node_js
node_js:
  - "10"

before_script:
  - npm install -g gatsby
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master

after_success:
  - npm run deploy
